package com.vaadin.devon.dummy;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.devon.dummyImpl.AbstractVaadinChartExample;
import com.vaadin.ui.Component;
import com.vaadin.ui.Grid;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DummyChartDesign extends AbstractVaadinChartExample {
	protected Grid grid;

	public DummyChartDesign() {
		Design.read(this);
	}

	@Override
	protected Component getChart() {
		// TODO Auto-generated method stub
		return null;
	}
}
